// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiBkhnaDKSuMwTLEFGiOHs-Hc7I7qeAWU',
    appId: '1:461853612383:web:5a0f59970639e556d53eea',
    messagingSenderId: '461853612383',
    projectId: 'ecomrce-b145c',
    authDomain: 'ecomrce-b145c.firebaseapp.com',
    storageBucket: 'ecomrce-b145c.appspot.com',
    measurementId: 'G-914F8BS43K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUq37xZCDtq7Byv-Ez5_iR40g5q9wBDac',
    appId: '1:461853612383:android:529dc0c686aabb33d53eea',
    messagingSenderId: '461853612383',
    projectId: 'ecomrce-b145c',
    storageBucket: 'ecomrce-b145c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvsL7_ApofnlQGNXZcdwWQlg8985HrQb8',
    appId: '1:461853612383:ios:033d0483350a87aad53eea',
    messagingSenderId: '461853612383',
    projectId: 'ecomrce-b145c',
    storageBucket: 'ecomrce-b145c.appspot.com',
    androidClientId: '461853612383-3fdl70p67nakuvk54pskiccoddbd0pkc.apps.googleusercontent.com',
    iosClientId: '461853612383-c6qljdn03o0fumsqikfs2aaoad57d0bl.apps.googleusercontent.com',
    iosBundleId: 'com.zosrtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvsL7_ApofnlQGNXZcdwWQlg8985HrQb8',
    appId: '1:461853612383:ios:3da2bfe60d32ea17d53eea',
    messagingSenderId: '461853612383',
    projectId: 'ecomrce-b145c',
    storageBucket: 'ecomrce-b145c.appspot.com',
    androidClientId: '461853612383-3fdl70p67nakuvk54pskiccoddbd0pkc.apps.googleusercontent.com',
    iosClientId: '461853612383-8hsfbrvp6d7da7f9ui65tcleo7p27lv4.apps.googleusercontent.com',
    iosBundleId: 'com.zosrtest.RunnerTests',
  );
}
